#ifndef CMDLINE_STATUS_H
#define CMDLINE_STATUS_H

typedef enum 
{
  CMDLINE_OK = 0,

  CMDLINE_LEX_UNBALANCED_QUOTE,
  CMDLINE_LEX_UNFINISHED_ESCAPE,

  CMDLINE_PARSER_ERROR,
  CMDLINE_EXPRESSION_ERROR
} CmdlineParserStatus;

#endif /* CMDLINE_STATUS_H */

